"""Trusted task data, admission, lineage, and sealing APIs."""

from reporl.tasks.admission import (
    AdmissionEvidence,
    AdmissionFailure,
    LeakScan,
    LicenseReview,
    RegressionExpectation,
    SnapshotKind,
    SnapshotValidation,
    TaskAdmissionResult,
    TestRunOutcome,
    validate_task_admission,
)
from reporl.tasks.canonical import artifact_sha256, canonical_json, canonical_sha256
from reporl.tasks.dataset import (
    DatasetManifest,
    DatasetTaskEntry,
    SealedSplitAudit,
    SealedSplitIssue,
    SplitDigest,
    SplitSeal,
    audit_sealed_split,
    seal_dataset_manifest,
    split_assignment_sha256,
)
from reporl.tasks.lineage import (
    LineageAuditReport,
    LineageConflict,
    LineageConflictKind,
    RepositoryRecord,
    audit_repository_splits,
    normalize_source_url,
)
from reporl.tasks.loader import (
    TaskDataError,
    load_json,
    load_jsonl,
    load_task_specs_json,
    load_task_specs_jsonl,
    load_verifier_manifests_json,
    load_verifier_manifests_jsonl,
)
from reporl.tasks.manifest import (
    AgentTestSuite,
    ArtifactReference,
    EnvironmentVariable,
    TrustedCommand,
    VerifierManifest,
    VerifierTestSuite,
)

__all__ = [
    "AdmissionEvidence",
    "AdmissionFailure",
    "AgentTestSuite",
    "ArtifactReference",
    "DatasetManifest",
    "DatasetTaskEntry",
    "EnvironmentVariable",
    "LeakScan",
    "LicenseReview",
    "LineageAuditReport",
    "LineageConflict",
    "LineageConflictKind",
    "RegressionExpectation",
    "RepositoryRecord",
    "SealedSplitAudit",
    "SealedSplitIssue",
    "SnapshotKind",
    "SnapshotValidation",
    "SplitDigest",
    "SplitSeal",
    "TaskAdmissionResult",
    "TaskDataError",
    "TestRunOutcome",
    "TrustedCommand",
    "VerifierManifest",
    "VerifierTestSuite",
    "audit_repository_splits",
    "audit_sealed_split",
    "artifact_sha256",
    "canonical_json",
    "canonical_sha256",
    "load_json",
    "load_jsonl",
    "load_task_specs_json",
    "load_task_specs_jsonl",
    "load_verifier_manifests_json",
    "load_verifier_manifests_jsonl",
    "normalize_source_url",
    "seal_dataset_manifest",
    "split_assignment_sha256",
    "validate_task_admission",
]
